const PROJECTS_DATA = [
  {
    "id": "port_city",
    "index": "01",
    "title": "A Port City - Coney Island",
    "category": "Academic Work",
    "location": "Coney Island, NY, USA",
    "university": "University of Cincinnati",
    "role": "Collaborative Design",
    "software": "Revit, AutoCAD, Photoshop",
    "start_page": 3,
    "end_page": 9,
    "pages": [
      "03.jpg",
      "04.jpg",
      "05.jpg",
      "06.jpg",
      "07.jpg",
      "08.jpg",
      "09.jpg"
    ],
    "texts": [
      "01 A PORT CITY An equal collaborative design from the University of Cincinnati, this project designs a resilient Industrial Zone for the flood-prone landscape of Coney Island. The primary goal is to maintain full operationality by identifying high-risk zones within the 100-year flood line. The design implements a system of flood walls and a centralized elevated platform situated above the flood level. This ensures that even during peak flooding, movement between buildings remains uninterrupted. By merging protective barriers with elevated circulation, the project provides a practical infrastructure that preserves urban connectivity and industrial safety in high-water conditions.",
      "I - RAISED PLATFORM (UP!) 2 - PUNCTURED PLATFORM (DOWN! Historically, the site's 100-year flood level occurred every decade, making the previous park's maintenance unsustainable. Our design shifts from resisting water to managing its flow. By utilizing natural high points, we implemented an elevated platform system for core functions. The architecture allows floodwaters to enter and exit the site freely, preventing stagnation and ensuring the industrial zone remains functional and easy to maintain post-flood. HIGH INDUSTRY LIGHT INDUSTRY SHI MARINA INDUSTRY ENTRY RIVERFRONT FOR RESIDENCE RIVER FRONT FOR RESIDENCE RESIDENCE ENTRY LOW DENSITY ENTERTAINMENT RIVERFRONT FOR RESIDENCE HIGH DENSITY HOUSING HIGH DENSITY ENTERTAINMENT EXPLODED AXON PORT - PROMENADE PLATFORM BUILDIN S OAD NETWORK HIO R VERBEN",
      "acne n liiilllill 2/ lillillill liiilllill a ROOF PLAN 115'",
      "SITE ISOMETRIC FROM SE 4.2",
      "GROUNDFLOOR PLAN SCALE The project utilizes a sophisticated dual-layer strategy that pairs an expansive elevated platform for uninterrupted circulation with a ground level programmed for high-intensity use. Through meticulous topographic gradation, engineered slopes work to direct floodwaters away from core building footprints. This \"dry island\" approach establishes secure zones for critical infrastructure while strategically positioning open-air structures to manage natural hydraulic flow. To ensure superior spatial quality, the design employs wide structural spans and high clearances that prevent the under-platform environment from becoming dark or cluttered. By prioritizing natural light, the ground plane remains safe and inviting. Recognizing that flooding is infrequent, this lower level is optimized for adaptive programming, accommodating public interaction and industrial storage. This comprehensive approach maximizes site efficiency, ensuring every square foot remains a productive asset by reducing \"dead space\" to an absolute minimum. lillillill",
      "Air FEMA 502' REG. FLODWAY PORT RIVER BUILD UP: REPEL WATER COMMERCIAL MIXED USE LAKE ENTRY LIFT UP: PROMENADE - TRANSVERSE SITE SECTION 75'"
    ],
    "description": "01 A PORT CITY An equal collaborative design from the University of Cincinnati, this project designs a resilient Industrial Zone for the flood-prone landscape of Coney Island. The primary goal is to maintain full operationality by identifying high-risk zones within the 100-year flood line. The design implements a system of flood walls and a centralized elevated platform situated above the flood level. This ensures that even during peak flooding, movement between buildings remains uninterrupted. By merging protective barriers with elevated circulation, the project provides a practical infrastructure that preserves urban connectivity and industrial safety in high-water conditions."
  },
  {
    "id": "car_museum",
    "index": "02",
    "title": "Detroit Car Museum",
    "category": "Academic Work",
    "location": "Detroit, MI, USA",
    "university": "University of Cincinnati (DAAP)",
    "role": "Individual Studio Project (Fall 2024)",
    "software": "Rhino, Grasshopper, 3ds Max, V-Ray",
    "start_page": 10,
    "end_page": 15,
    "pages": [
      "10.jpg",
      "11.jpg",
      "12.jpg",
      "13.jpg",
      "14.jpg",
      "15.jpg"
    ],
    "texts": [
      "DETROIT CAR MUSEUM 01 This design envisions the Detroit Car Museum as a contemporary landmark that blends creativity with functionality a vibrant space that celebrates the city's rich automotive heritage while fostering community interaction and cultural continuity. - This project was developed as part of my Fall 2024 studio at the University of Cincinnati, DAAP",
      "SITE ANALYSIS DETROIT PARKING SPACES RESIDENCIAL SPACES COMMERCIAL SPACES INDUSTRIAL SPACES GREENSP CE RAILWAYS SPACES SITE SITE BRIEF I. Cen CAR MUSEUM - THE HEART OF DETROIT The proposed Car Museum is envisioned as the heart of Detroit, globally recognized as the cradle of the auto- mobile industry. More than a repository of cars, it serves as a cultural landmark reflecting the city's rich automo- tive history and enduring spirit of innovation. At its core is a revolving conveyor belt wrapping around the facade, displaying cars inside and outside. Inspired by Detroit's pioneering assembly line, this reinterpreta- tion turns the conveyor into an architectural symbol bridging past and present. The moving display trans- forms the facade into a living exhibition, visible to both visitors and passersby, making the museum an active part of city life. The museum is also conceived as a contemporary gathering place. Reviving Detroit's legacy of races, rallies, and drag events, it includes dedicated zones for displays and drag races, ensuring it remains dynamic and engaging. Visitors are invited not just to view cars as history but to experience the thrill and culture surround- ing them. DESIGN DEVELOPMENT Assembly chain Car show Detroit Dragway Interactive Mechanical Space Form Idea RACING Building Form Form Development The chosen site, located near the General Motors headquarters in downtown Detroit, is deeply rooted in the city's automotive history. This symbol- ic location offers more than physical context; it embodies the spirit of Detroit's industrial legacy. GM, along with surrounding automotive land- marks, provides a powerful backdrop for the museum, ensuring the design resonates with the city's larger narrative rather than standing as an isolated intervention. Its rich history, visibility, and accessibility make it an ideal setting to celebrate Detroit's automotive heritage while contributing to downtown's cultural vitality. SWOT - Car Museum Site Strengths: Prime site near GM HQ, highly visible and accessible, rich in Detroit's automotive heritage Weaknesses: Limited space for expansion, po- tential noise and traffic from surrounding roads Opportunities: Serve as a cultural hub, host in- teractive exhibits, and offer educational pro- grams on automotive history Threats: Competing developments may reduce visibility, and congestion or limited parking could affect visitors EPORT",
      "SITE PLAN 01 - Public Plaza A vibrant pedestrian-friendly space that draws people into the site and addresses the lack of quality public areas nearby. As a buffer and transition zone, it creates a welcoming entry, a landmark edge, and a lively hub for visitors and the community. 03 - Amtrak Station The existing station is renovated and integrated into the masterplan to improve connectivity and accessibility. Preserving its historic role while updating its function boosts regional links, increases footfall, and posi- tions the site as a key urban node. W MILWAUKEE AVENUE ENTRWEXIT OPEN CAR DISPLAY ENTRY/EXIT ENTR /EXT W MILWAUKEE AVENUE ENTRY/EXIT AMTRAK STATION 02 - Main Museum The museum showcases cars from early models to modern icons within spacious double-height interiors. A revolving conveyor belt encircles the building, displaying cars in motion as a tribute to Detroit's assevmbly line heritage and the Ford Model T. 04 - Display & Event Space An outdoor area for rotating car shows that attract enthusiasts and the public, doubling as parking when inactive. Linked with E. Baltimore Avenue, it also hosts organized drag races, cele- brating Detroit's racing tradition. 01 03 02 ENTRY/E ENTRY/ ENTRY/EXIT CAR 'ROV *TER'OR ENTRY,' EXIT E MILWAUKEE AVENUE POINt MOOERN CAR COLLECT'ON SERVICE PER ENT COLLEC WIN A ERv'1CE PONT LOBBY MOBIUS / gtNtACE CAR COLLECTION DRAG RACE OPEN CAR SHOW WING B CAR OSPLAY J ORAGRACE VIEW STPAMP E BALTIMORE AVENUE ENTRY LOANNCOOCK i ADMI rr\u0007r-r-i OFFICES: SERVICE ROOM IT",
      "CAR MUSEUM BLOCK The central building houses the Car Museum, showcasing vehicles ranging from early models to contemporary innovations. The interior design emphasizes open- ness, incorporating double-height volumes and spatial variety that enhance the visitor experience. A defining feature of the museum is a revolving conveyor belt that wraps around the facade, displaying cars in continuous motion. This element abstractly references Detroit's assembly line heritage, particularly the revolution- ary impact of the Ford Model T, while transforming it into a dynamic architectural expression. FIRST FLOOR PLAN LOBBY - NTRYtEXtT---- MOBIUS STIP ART INSTLATION JIK CAR DISPLAY DRAG RACE VIEW STNAMP i v w : LOADING DOCK I ENTRY PERANENT COLLECTIOti1 - LIFT LOBBY PERMANENT COLLEFTION - WING B : cocona: ADMI OFFICES: VINTAGE CAR COLLECTION SERVICE ROOM",
      "2nd FLOOR PLAN 3rd FLOOR PLAN 4th FLOOR PLAN WAY SECTION A-A' SECTION B-B' 0-4 CNC ARO?\u0007.CS r Guuk.)uu -e.o.n.nn.o.n.-q OOCX CROC Building Narrative: The design of the building is centered on crafting an immersive spatial journey that celebrates Detroit's rich automotive heritage. Conceived as more than just a museum, the space becomes an experi- ence that captures the city's enduring relationship with innovation, craftsmanship, and motion. From the welcoming entrance that draws visitors inward to the carefully sequenced exhibition zones, every spatial transition is designed to narrate a story of machines, makers, and the spirit of progress. The plan unfolds through interconnected volumes that encourage exploration and curiosity, with open dou- ble-height galleries showcasing iconic car models. Elevated walkways and ramps allow visitors to ex- perience vehicles from multiple perspectives, much like observing a moving assembly line. Strategic visual corridors connect interior spaces to exterior display courts, creating a continuous dialogue be- tween architecture and landscape. Materiality and spatial rhythm reflect Detroit's industrial identity, using steel, concrete, and glass to ex- press strength and transparency. The circulation embodies the city's motion, guiding visitors through time from the pioneering era of the Model T to today's modern automotive design transforming history into a living architectural experience that captures the rhythm, energy, and pride of Detroit's car-mak- ing legacy.",
      "Exploded Axon Perspective Section Concept Narrative: The design of the Detroit Car Museum is inspired by the city's legacy of motion, innovation, and crafts- manship. The architecture draws from Detroit's identity as the birthplace of the modern automobile, translating the energy of production lines, workshops, and urban streets into spatial experiences. The building's form and circulation reflect a sense of continuous movement - where visitors journey through spaces that unfold like the stages of car-making itself, from creation to celebration. A defining element within this concept is the dynamic conveyor belt that loops around the central ex- hibition zone, symbolizing Detroit's revolutionary assembly line. This moving feature not only displays vehicles in motion but also reinforces the city's spirit of progress and innovation. Open galleries, lay- ered walkways, and framed visual connections allow visitors to experience the displays from multiple levels and perspectives, creating a sense of interaction and flow. Each space, whether an exhibit hall, viewing bridge, or public atrium, contributes to a collective narrative - one that honors Detroit's past while embracing its evolving creative future."
    ],
    "description": "DETROIT CAR MUSEUM 01 This design envisions the Detroit Car Museum as a contemporary landmark that blends creativity with functionality a vibrant space that celebrates the city's rich automotive heritage while fostering community interaction and cultural continuity. - This project was developed as part of my Fall 2024 studio at the University of Cincinnati, DAAP"
  },
  {
    "id": "sports_complex",
    "index": "03",
    "title": "Sports Complex Academy",
    "category": "Thesis Project",
    "location": "Thiruporur, Chengalpattu, Tamil Nadu, India",
    "university": "Anna University (10th Semester)",
    "role": "Individual Thesis",
    "software": "Revit, Lumion, Photoshop, Space Frame design",
    "start_page": 16,
    "end_page": 27,
    "pages": [
      "16.jpg",
      "17.jpg",
      "18.jpg",
      "19.jpg",
      "20.jpg",
      "21.jpg",
      "22.jpg",
      "23.jpg",
      "24.jpg",
      "25.jpg",
      "26.jpg",
      "27.jpg"
    ],
    "texts": [
      "03 SPORTS COMPLEX This is a thesis project done during my 10th semester. The site is located in the Thiruporur panchayat town in Chengalpattu district in the Indian state of Tamil Nadu, which is a newly developing region in the city. To design a Sports training academy with a capacity of 35000-40000 people that provides full-time training facilities to young athletes and aspiring sportsmen, which helps in breaking the \"single-sport\" CUItl.Jre of our country and brings \"multi-sportingl' CUIture as part of an urban lifestyle Click logo to watch the walkthrough on youtube",
      "FORM EVOLUTION Deciding on the OSR's placement and setbacks in accordance with the site's guidelines and regulations. 01. The stadium shape was changed to ellipse shape for an expansive view both inside and toutside , favouring the limitless perspectives of circles over the angles of rectangle, and optimizing seating space dynamics. 03. The design and entry configuration for each blocks are finalized. The administrative and indoor block are divided into two sections,The building boasts a spacious entrance, ensuring a welcoming ambiance for visitors. 05. As the stadium occupies up the majority of space and is essential part to the design, it was placed in the center as a focal point. The requirements for this complex are splitted into different zones ensuring efficient utilization and convenient access for users from different entry points and other buildings in this complex. Entry points to the site is decided Roads, pavements, landscapes, surface parkings, etc, are planned and designed based on specific requirements and needs outlined in the project specifications 06. Considering the volume of users at the stadium during matches, an emphasis was placed on the open space ratio. A distribution of 40% to the building and 60% to open spaces was prioritized to optimize the overall functionality and comfort of the stadium environment",
      "CRYSTALINE ARCHITECTURE Crystaline architecture refers to the style of architecture which draws inspiration from the structure and aesthetics of crystal. It consists of diagonals, visible frames and triangles to create visually striking and fututristic appearance. Its materials are not only glass but also stone and concrete, Its intricate patterns can be transformed into architectural form. STADIUM LIT UP DURING EVENTS TO ACT AS A MAIN ATTRACTION POINT STADIUM FUNCTIONALITY The stadium's primary design was determined by the layout of the tracks and views. In addition to housing a single sport, it is built to accommodate several events and sports at various times in order to generate income. OOTBALL COURT ATHELETIC TRACK CONCERT STADIUM SPORTS EVENTS",
      "POLYCARBONATE kFlNt------ SPACE FRAME STRUCTURE PTFE SPACE FRAME STRUCTURE POLYURETHANE TRACK HYBRID TURF WITH A COMBINATION OF NATURAL GRASS AND SYNTHERTIC FIBRE SEATING GALLERY PRECAST CONCRETE WITH CHAIRS FOR SEATING",
      "EXIT ENT \u0007 {13. .61 i 09 po 0000 28 27: \u000726 25 24 31 10 40 - '139. 40 pooy ss0d/(8 WVO OMR Bypass Road 23 = 00 22 .21 20 19 05 '16 12 03 00 01 ENTRY 06 09 14 07 ENTR 13 16 & ssoa LEGEND 01 . Stadium 02. Indoor Stadium 03. Players Accodmoation 04. Practice Studio 05. MLCP 06. Practice Court Entry 07. Main Entry 08. Indoor Stadium Entry 09. Indoor Stadium Parking 10. Players Parking 11. Water Body at Site 12. Crossover Bridge 13. Open Landscape 14. Landscape With Seating 15. OAT 16. OSR 17. Display TV 18. Landscape with water body 19. Open Landscape 20. Closed Landscape Site Location : Old Mahabalipuram Rd, Thiruporur, Tamil Nadu 6031 Site Area : 83 - Acres Land Use : Recreational",
      "STADIUM ISOMETRIC VIEW FOOTBALL COURT CONCOURSE SEATING GALLERY ATHLETIC TRACK 00 0",
      "GROUND FLOOR PLAN 35 36 37 38 39 34 40 32 33 go 00 e 42 31 6.67 13.01 3.00 43 29 30 STADIUM M DIA CEN E 450SQ.M 68.00 9.54 44 45 28 46 27 3.00 13.00 47 26 4.85 PLAYERS BOCH 25 2.12 13.00 1 .00 DIS +0 VL 24 23 3.00 22 20 00 3.00 RESERVED ASST Em-rs 24.36 Faa 300 749 5.77 6.58 FLOOO LMTS 17 8.55 11. STADIW 40 5.13 -IDC 48 14 13 12 11 FOOTBALL GROUND 10 CLEAR SPACE SEATING GALLERY CONSSESION FOOD STALL CIRCULATION SPACES RETAIL SPACES RESTROOMS SERVICE CORE SERVICES VVIP/ VIP LOUNGE ATHLETIC TRACK",
      "28 01. 33 36 38 39 40 41 03. 36 31 32 31 32 (29 30 45 27) 26 48 27 25 26 48 24 23 24 22 23 21 20 24 A1 21 19 18) 19 18 12.34 17 16 15 14 13 12 11 10 17 16 15 14 13 12 61 10 02. 35 36 37 39 40 35 36 37 31 32 42 43 31 32 42 27 27 24 4M WIDE - GANGWAY 4m 4M WIDE-GANGWAY 46 28 48 26 *7.7i.VL 25 24 23 23 22 22 21 21 20 19 19 (29 45 46 47) 28 46 CD 38 39 40 41 42 41 33 41 45) 29 30 45 18 17 16 15 14 13 12 11 10 18 17 16) 15 14 13 12 11 10 46 [48 FOOTBALL GROUND CLEAR SPACE SEATING GALLERY CONSSESION FOOD STALL CIRCULATION SPACES RETAIL SPACES RESTROOMS SERVICE CORE SERVICES VVIP/ VIP LOUNGE ATHLETIC TRACK 01. SEATING GALLERY PLAN ENTRY TO MAIN GALLERY VVIP Lounge VVIP Lobby VVIP Executive suit room VVIP pantry V VIP servery 02. FIRST CONSSEISION LEVEL Stadium Services Stadium office space Concession Food point Stall Restroom's Entry to the middle tire Gallery 03. SHOPPING AND FOOD COURT Stadium Services Service area for stalls Temporary stalls AHU Services Merch Shops VIP Lounge Stewards Pantry 04. 2ND CONSSEISION LEVEL Entry to the gallery Merch shop Concession food Point Service area Restroom's VVIP Lounge VVIP Lobby VVIP Executive suit room",
      "BRIDGE CONNECTING MAIN STADIUM AND MLCP. STADIUM SECTION AA' gtt t t OPEN AIR THEATHRE VIEW MAIN STADIUM VIEW TOP FLOOR LOBBY SPACE SERVEE FLOOR TOLET SERVICE FLOOR WA QUEUING AREA SERVCE FLOOR DlSPtAY TOP FLOOR LOBBY COWESSKN PRIVATE LOUNGE FOOD COWESsm FLOOR FLO(R 13.00",
      "INDOOR PRACTISE COURT PUBLIC CIRCULATION SERVICE CIRCULATION Standard floor plans with only the COUrtS adjusted accordingly on all floors. Service cores AHU Rooms Storage rooms Pantry Dinning area Ordering areas Players dinning area Players Medical room Discussion room Equipment storage Restrooms Shower areas COUrtS available archery handball Takewondo Judo Fencing COUrt Badminton ARCHERY HANDBALL COURT TAKE-WONDO AND JUDO FENCING COURT GROUND FLOOR DISPLAY COURT INDOOR STADIUM AND ACCOMADATION GROUND FLOOR MULTILEVEL CAR PARKING (MLCP) PLAN FOUR WHEELER PARKING 12 11 13 10 14 15 16 STADIUM ACCOMADATION Lounge Admin offices Enquiry room I SAI office SFI office Data storage rooms I Suite rooms Arcade INDOOR BASKETBALL COURT I Basket ball court I Display zones Food court Kitchen I Warm Up zones I Media control zone Service rooms I Locker rooms I Discussion rooms I Storage TWO WHEELER PARKING"
    ],
    "description": "03 SPORTS COMPLEX This is a thesis project done during my 10th semester. The site is located in the Thiruporur panchayat town in Chengalpattu district in the Indian state of Tamil Nadu, which is a newly developing region in the city. To design a Sports training academy with a capacity of 35000-40000 people that provides full-time training facilities to young athletes and aspiring sportsmen, which helps in breaking the \"single-sport\" CUItl.Jre of our country and brings \"multi-sportingl' CUIture as part of an urban lifestyle Click logo to watch the walkthrough on youtube"
  },
  {
    "id": "performing_arts",
    "index": "04",
    "title": "Performing Arts Center",
    "category": "Academic Work",
    "location": "Anna Salai, Triplicane, Chennai, India",
    "university": "Anna University",
    "role": "Individual Studio Project",
    "software": "AutoCAD, SketchUp, V-Ray, Tensile Roof design",
    "start_page": 28,
    "end_page": 37,
    "pages": [
      "28.jpg",
      "29.jpg",
      "30.jpg",
      "31.jpg",
      "32.jpg",
      "33.jpg",
      "34.jpg",
      "35.jpg",
      "36.jpg",
      "37.jpg"
    ],
    "texts": [
      "04 PERFORMING ARTS CENTER The project aim is to design a Performing arts center with quality and character of environment appropriate to promote classical performing arts with relevance to our country. The center will be an integrated complex which offers an amalgamation of guru-shisya and modern teaching pedagogy. It is also an effort to rejuvenate and use the space in an urban context for public interaction and for promoting enhanced collaborative work among artist. The project focuses on providing infrastructure & knowledge resource which would act as a magnet to those practicing or interested in art potential. Attempt will be made to promote learning and interest towards the arts through observation, interaction and practise. \u0007tV Click youtube logo to watch the walkthrough on next page",
      "SITE ANALYSIS The site has been analysided according to the wind and sun directions and designed building and orientation of it accordingly. the site is located near COOIJm river ehich once was a river and now changed into sewage. The N VV side Of the site has heavy sound from therailway tracks and has bad PERIYAR BRIDGE SWAMI SIVANANDA SALA I ANNA SALAI The site is located in the heart areas of the city. The roads near the site has heavy traf- fic and has traffic noises all the time. The red zones are heavily traffic zone areas. The blue circles are important nodes. These factors are also taken into consider- ation while designing. AUDITORIUM PARKING ENT* VISITORS PARKIN PUBLIC SPACES SEMI PUBLIC PRIVATE SPACES OSR PARKING Entry is decided and other spaces are zoned according to public, semi public ,private spaces and parking Osr is designed according to the site analysis. odour due to cooum river. FORM DEVELOPMENT STAGE I - Building spot was formed considering the setback rules and regulations. - Separate portion of the site was dedicated to OSR. Practice Rooms & Accommodation Studios---, Auditorium so\\ SQ/Qi STAGE II - Zoning based on spatial requirements and functions. Defining entry and exit points for public and service access. Retail shops OAT -Black box swami STAGE III Due to traffic and noise produced by vehi- cles in roads and railway tracks. Buffer zones are created in front to reduce the sounds are pollution. so\\ 00 so\\ swami STAGE IV Shielding essential areas with roofs. Catering to the specific demand for parking cars and bikes. O VEHICULAR SOUND NORTH LIGHT WIND DIRECTION (SE AND NW) SUN PATH (EAST TO WEST) BAD ODOUR SOUND FROM RAILWAY TRACK NODES TRAFFIC ZONES BUFFER ZONES NODES - Carving out elements to generate openings for ventilation and lighting. - Crafting the essential volume to accomodate the program.",
      "SITE PLAN EXIT 05 05 05 02 LEGEND 01 . Art Center main lobby 02. Auditorium 03. Exhibition gallery 04. Entry podium 05. Core ENTRY 06. Food court 07. Landscape 08. Conference room 09. Library 10. Main Parking 03 1 1 . Temporary Parking 12. Bike Parking 13. Service Parking 14. Auditorium Entry 15. OSR 05 09 Site Location . Anna Salai, Triplicane, Chennai, Tamil Nadu 600005 15 Land Use : Site Area : 7.2 - Acres",
      "Aerial perspective of a performing arts center under daylight. Aerial perspective of performing arts center during night time.",
      "MAIN MATERIALS USED IN THE BUILDING The tensile is designed in a way that the curves direct the seasonal winds to the courtyard below them. The winds gets pulled in automatically due to the shape for the roof. Tensile structures are more cost effective and east to maintain, adds more aesthetic value when done in a large scale. TENSILE ROOF SPACE FRAME BRICK CONCRETE PLASTER GLASS DETAIL-A Tree column is used to support large span buildings and tensile roofs as well as pro- vides a visual interest to the space. Tensile columns is a very efficient to minimise the number of columns, giving a large open space. The columns are fixed in the space frame for support on one side and the other side to the ground. Material used is metal. Performin OCH",
      "PERFORMING ARTS CENTER - PERSPECTIVE VIEW",
      "BENGALURU NORTH UNIVERSITY KOLAR Bengalur North University Kolar is a famous university located at Kolar, The requirments was to create a design which is rustic and robust design unl liillii! ace.",
      "FLOOR PLANS FIRST FLOOR PLAN 05 15 06 16 05 19 10 13 05 05 14 18 11 01 04 10 03 05 01 05 08 LEGEND 01 . Accommodation 02. Auditorium-I st Floor 03. Main Lobby 04. Kitchen 05. Core 06. Stall 07. Landscape 08. AHU room 09. Black Box 10. Drama Studio 1 1 . Photography Studio 12. Dance Studio 13. Mech.Room 14. Elec.Room 15. Storage 16. Rehersal Room 17. AHU Room 18. Auditorium Seating 19. Retail 20. Main Stage 02 SECOND FLOOR PLAN 05 LEGEND 06 08 01 02 03 O 01 . Indoor Seating 02. Auditorium 03. Black Box (Catwalk) 04. Outdoor Seating 05. Accommodation 06. Open Lobby 07. OAT Lobby 08. Landscape 09. Black Box Service Bay 05",
      "Auditorium 12 05 14 13 06 05 LEGEND 10 09 05 01 06 05 _2(12 (.13 04 10 05 14 01 LEGEND 01 . Auditorium-I st Floor 02. Retail 03. Restroom's 04. AHU Room 05. Core 06. Mechanical Room 07. Electrical Room 08. Storage 09. Rehearsal Room Auditorium Entry 10. 07 05 07 02 10, 03 04 18 03 10. Storage 09 05 02 10 106 05 LEGEND 01 01 . Art Center main Entry 02. Auditorium Parking Entry 03. Ticket Counter 04. Pantry 05. Core 06. Retail 07. Main Stage 08. Orchestra Pit 09. Rehearsal Room SECTION A-A' LEGEND 01 . Art Center main Entry 02. Auditorium Parking Entry 03. Ticket Counter 04. Pantry 05. Core 06. Retail 07. Main Stage 08. Orchestra Pit Rehearsal Room 09. 11. Green Room 12. Control Room 13. VIP Entry 14. VIP stay 15. VIP Lounge 16. Space Under Gallery 17. Gallery Space 18. Restroom's Area under seating filled to avoid empty and void space and giving an solid floor and covering it with acoustical metrials will improve acoustics An orchestra pit in an au- ditorium is a sunken area,Where musicians play, hidden from the stage's array beneath the performers. 11. Main Gallery 12. Main Stage 13. Orchestra Pit 14. Projector Room 01 . Auditorium 2nd Floor 02. Catwalk 03. Main Lobby 04. Retail 05. Core 06. Restroom 07. Main Stage 08. Storage 09. Black Box 10. Open Seating I Ill 108 05 01 INTERIOR VIEW A buffer zone is maintained between the auditorium house and restroom space to maintain both the places undisturbed I Projector room is behind the audience and placed at the height of 2.5m so that while people are moving near the projector have enough space so they don't hinder it. Entry to auditorium is located near the reception so that the visitores ocan be tracted to it easily 1 01 01 01 1 01 01 01 01 01",
      "FRONT ELEVATION SECTION A-A' SECTION B-B' DDz-zgZ"
    ],
    "description": "04 PERFORMING ARTS CENTER The project aim is to design a Performing arts center with quality and character of environment appropriate to promote classical performing arts with relevance to our country. The center will be an integrated complex which offers an amalgamation of guru-shisya and modern teaching pedagogy. It is also an effort to rejuvenate and use the space in an urban context for public interaction and for promoting enhanced collaborative work among artist. The project focuses on providing infrastructure & knowledge resource which would act as a magnet to those practicing or interested in art potential. Attempt will be made to promote learning and interest towards the arts through observation, interaction and practise. \u0007tV Click youtube logo to watch the walkthrough on next page"
  },
  {
    "id": "freelance_work",
    "index": "05",
    "title": "Freelance Work & Interiors",
    "category": "Freelance",
    "location": "India & USA",
    "role": "Lead Designer",
    "software": "Illustrator, Photoshop, AutoCAD, 3ds Max",
    "start_page": 38,
    "end_page": 41,
    "pages": [
      "38.jpg",
      "39.jpg",
      "40.jpg",
      "41.jpg"
    ],
    "texts": [
      "05 FREELANCE WORKS WHITEHORSE LOGO DESIGN- CALIFORNIA, USA Whitehorse is a venture capital private limited company that helps investors find sources of funding for their businesses in addition to helping them identify the best startup to invest in. I was tasked with designing the logo for the business. There are two partners for this company: one is located in India, and the other is in California, USA. Every web designer and UI/UX designer who collaborated and worked with me on this project was from California. An exquisite unicorn that is constantly developing is portrayed in the logo. WhiteHorse Pitch your Startup Start Investing Become an Advisor Sign Up Sign In Democratizing Venture Capital: Startup Investments Made Easy Join our syndication platform for collaborative investing, where startups and investors thrive together. Explore iiit Cross-Borderstartup investment opportunities, highly vetted b o r experienced team. investment opportunities in diversified dynamic startup landscape SIGNUP FOR FREE , aiming to minimize risk in the inherently",
      "Design I WHIT Final Design Design 2 WHITE HORSE ORSE Design 3 WHITE HORSE Whitehorse company official logo designer certification DocuSign Envelope ID: 96E7C415-C51C-46ED-A5B2-DA79013EEBDC WhiteHorse WHITEHORSE CLOBAL VENTURE CAPITALIST PRIVATE LIMITED Date :21-Nov-2023 To Whomsoever it may concern This is to certify that Mr. Raam Prakash Kalaiyarasan has demonstrated exceptional creativity and proficiency in designing and developing the logo for our upcoming tech platform. The logo is a Trademark and Copyright of WhiteHorse Global. Raam's ability to grasp the vision of our company and translate it into a meaningful visual representation is truly commendable. His contribution has been invaluable, and his work is highly appreciated by our firm Ravi Subramanian DocuSigned by: C25COAB86694432. Signature. Founder & CEO WhiteHorse Global VC Pvt Ltd, Fremont, California, USA. Mobile - 001-408-368-8845 USA: WhiteHorse Global VC, Fremont, California - 94538, Phone : 408-368-8845 INDIA :WhiteHorse Global VC Private Limited, No.100 IP Nagar, Global Hospital Road, Chennai-600100, Phone: 0091-8939656375.",
      "CASAGRAND - INTERIOR DESIGN I had the opportunity to work on one of Casagrand's interior projects. Casagrand is a well-known real estate company. Creating a place with a contemporary feel was the primary goal of the design. Every place was thoughtfully created. Working on this project allowed me to get extensive knowledge about interior space materials."
    ],
    "description": "05 FREELANCE WORKS WHITEHORSE LOGO DESIGN- CALIFORNIA, USA Whitehorse is a venture capital private limited company that helps investors find sources of funding for their businesses in addition to helping them identify the best startup to invest in. I was tasked with designing the logo for the business. There are two partners for this company: one is located in India, and the other is in California, USA. Every web designer and UI/UX designer who collaborated and worked with me on this project was from California. An exquisite unicorn that is constantly developing is portrayed in the logo. WhiteHorse Pitch your Startup Start Investing Become an Advisor Sign Up Sign In Democratizing Venture Capital: Startup Investments Made Easy Join our syndication platform for collaborative investing, where startups and investors thrive together. Explore iiit Cross-Borderstartup investment opportunities, highly vetted b o r experienced team. investment opportunities in diversified dynamic startup landscape SIGNUP FOR FREE , aiming to minimize risk in the inherently"
  },
  {
    "id": "office_work",
    "index": "06",
    "title": "Professional Work - Studio 7",
    "category": "Professional Experience",
    "location": "Chennai & Tirupati, India",
    "role": "Project Architect (2023 - 2024)",
    "software": "Revit, AutoCAD, On-site Coordination",
    "start_page": 42,
    "end_page": 52,
    "pages": [
      "42.jpg",
      "43.jpg",
      "44.jpg",
      "45.jpg",
      "46.jpg",
      "47.jpg",
      "48.jpg",
      "49.jpg",
      "50.jpg",
      "51.jpg",
      "52.jpg"
    ],
    "texts": [
      "06 WORK - Studio 7 Architects During my time at Studio 7 Architects, I worked as a project architect, taking the lead role in design and overseeing site work. I was responsible for managing site activities, resolving on-site issues, and coordinating the on-site team to ensure smooth project execution. I handled detailed working drawings, documentation, and collaborated with structural consultants, contractors, and vendors. Client handling, material procurement, and conducting on-site inspections were also part of my role.",
      "HITS - SWIMMING POOL Hindustan Institute of Technology and Science is a famous private educational institute has both international and national students. The requirement was to design a building which has a beautiful aesthetical elevation. The main material used in the elevation was a polycarbonate sheet. Polycarbonate is a material which is translucent in nature. Compact to glass, this has less heat conductivity. The material is customizable that the size and flexibility of the material can be determined by the design needs. Polucarbon- ate was used in this design to give an unique identity and a landmark to this indoor swimming stadium at the university campus. Since I was the project architecte for this proj- ect I understood many techinical details and got hands on experince on this project.",
      "GROUND FLOOR PLAN FILTRATION ROOM 12XSM 60SQM (645 SQFT) LIFEGUARD ROOM 12X5M 60SQN (645 SQFT) GL0.oo 3.0 [9-10\"] 35.2 16.0 [52'-6\"1 FECELINE TENSILE ROOF WARM UP POOL IOX6M (32'X19'FT) 60SQ.M[645SF.T] 3.6 [11'-11 04 OUTDOOR SHOWER SWIMMERS 03 [19'$1 uueauu [9'-10'] 25.0 [82] 2.6 [8'-6\"J 0 0 03 LANE-I 3.0 [9'-10\"] 7'-9\"J LANE-2 LANE-3 LANE-4 LANE-5 2 X 40 s 6 40.7 [133'-6\"1 10 SYOWER SHOWER 9 DOON 0601) G [4305S LOBBY SPACE oo 52 F 01 3.0 9'-10 LANE-6 oan.AY GALLERY S64SQM(930SF.T1 \u0007 177 ENTRY GLO.45 ENTRY 31.2 [102-4\"] Facade Materail Polycarbonate Morning Noon Afternoon 9 3.0 [9'-10\"1 I DOON GttO.45 ROOM Cvm\u0007S) DOON GLO.OO 9.5 [31'-1\"1 .. '116 9 Vt 9 03 1.8 [5'-11\"] SCJASH bort.ta DCM.AY coen",
      "SECOND FLOOR PLAN FIRST FLOORPLAN GROUND FLOORPLAN SHOWER SHOWER 01 13.8 145'-2\"1 SQUASH WONCNS RESTROOM 04 OFFICE 04 C C PESTRO\" O IO [5'-11\"] C D D O 9349 3.2 COMMON LOQER 35.2 [115'-5\"1 GUN SHOOTNG 5.8 CLASSROOM 1 40SQN(4 FT) 3.7X7M(1S1 \u0007EXIT) CORRIDOR 17.3 (56'-9\"1 5.7 @ [18'-7\"J @ CLASSROOM 2 40SQM(430SQFT) 07 5.7X7MfT11\u0007xmo\u0007) PANTRY 9.0 [29'-7\"1 9.5 [31'-1\"1 1.8 [61 116 992 [31'-1\"1 BASEMENT FLOORPLAN 'lii 5.3 117'-6\"11 212 [69'-5\"1 17.3 [56'-9\"1 wrrH BALL I I I I II I II I I Ill Ill I II I I II II I I I I I I I II I I II I II I II I I I II I I 10.8 135'-6\"1 1.5 15] 9.5 [31'-1\"1 3.3 [10'-9 1.2 07 O O 5.7 CLASSROOM 3 40SQN(430SQFT) CT-LANG2<G REES) OWER OWER OWER boom ROOM (WOE(S) 9) 9 bCOtH mom B)0TH LOB*CE ExrkY 00 00': 00 oestt.YCOQ{U",
      "ADITHYA RESIDENCE A design-build residential project executed in Tirupati, involving complete responsibility from design to construction. Due to the site's distance from our office, the project was managed through remote coordination combined with frequent site visits. Procuring locally available materials and working with regional contractors shaped both design deci- sions and construction methods, offering valuable hands-on experience in site management and execution. \"lilt' \u0007'111 ,",
      "RENDER SITE IMAGES",
      "c D E 2'-6\" 14'6\" BEAM THIS DRAWING IS A COPYRIGHT. IT IS NOT TO BE REPRODUCED,COPIED HANDED OVER TO A THIRD PARTY OR USED FOR ANY OTHER PURPOSE OTHER THAN FOR THE PROJECT INVOLVED. *ALL DRAWINGS AND DIMENSIONS ARE IN FT 12-71 \" '-101\" Area Statement: Site Area: 4310.13 Sq.ft Stilt Floor area: 2645.54 sq.ft 1st Floor area: 2674.24 sq.ft 2nd Floor area: 2652.86 sq.ft Terrace Floor area: 846.56 sq.ft Total Buildup Area: 8819.22 sq.ft sum 42L VMM/ MMM/ / / MMM/ M ARCHITECTS STUDIO 7 ARCHITECTS Eb anel EB ROOM 161-0\" x 9' 0\" Eb panel UP 'Servo 11 lit' I LOBB Lift ope ing as er Vendor 10 11 12 13 15 1 Refer Grill te ++1'O\"lvl Schedule of Joinery Description Main Door Masonry Opening Bedroom Door Room Door Acoustic Door Service room Door Utility Door Toilet Door Toilet Door Gym door Pooja door Grill Gate Sliding Door Sliding Window Sliding Window Sliding Window Casement Window Sliding Window Sliding Window Top Hang & Fixed Window Sliding Window Casement Window Sliding Window Sliding Window Sliding Window Casement Window Casement Window Fixed Window Ventilator Ventilator Tag Width Tread: IC' SE BEDROO 16'-0\" x 9-7 Height BOTTOM Sill DRIVE WAY ANT ROOM .5\" x 12-3\" TOILET 2 3 5 6 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 OPI DI D5 GG SD WI W7 WIO WII KWI KW2 SWI VI 4'0\" 40\" 12'9\" Lintel No.s 4 4 7'0'i 8'0'l 19 ++1 '6\"lvl O'O\"lvl 18 17 STILT FLOOR 40' WIDE ROAD , BEAM 06 BOTTOM 8'0'1 7'0'1 Staircase detail 8'0'1 Bearn bottorn 2 65 TOTAL REVISION CLIENTS Mr. and Mrs. Adithya PROJECT Mr.Adithya residence DRAWING TITLE FLOOR PLAN- STILT FLOOR Plot No. PP Ill, Janani's Shri Nilayam Semmencherry, Chennai - 600 119. SCALE DATE 1:100 21-08-2024 DRAWING CODE DRAWN CHECKED",
      "45'-9\" 12-7 DS 1\" Drop 3' 11 II II II Ill 11 Area Statement: Site Area: 4310.13 Sq.ft Stilt Floor area: 2645.54 sq.ft 1st Floor area: 2674.24 sq.ft 2nd Floor area: 2652.86 sq.ft Terrace Floor area: 846.56 sq.ft Total Buildup Area: 8819.22 sq.ft 4+11 '5\"lvl 1\" SERVICE CORRIDOR 25-4.5' x 5-0\" sva HEN Tread:1'O\" Riser:5.75\" FRI WET TAL WITH FRI E BELOW rop ITCHEN 91-61 x 9 9 APPLIANCE COU R +6\" IVI WASHING VESSELS (SIT) 10 11 12 13 1 1 '6\"lvl 1 IUI If M Lift opening as erv ndor POWDER ROOM \"lvi 8'-7.5\" x 9' \" Drop TOILET 6'-3\" x 10'4.5\" ++11 '4\"lvl 1 \" Drop 4+11 '5\"lvI Schedule of Joinery Tag Width Sill Refer Duct detail SERVING TABLE DINING 17-6\" x 14-0\" STORA POOJA 81-0\" x 61-8\" MANDAP I II OPI Ili I 4+11 '6\"lvl 1 1'-6\" 4'-10 12-1.5\" x 101-6\" Ill 14'6\" BEAM oven 31'-3\" x 201-6\" TV WALL OFFICE BOOKSHELF Refer Sun shade detail Refer Duct detail Refer Sun shade detail 7/7/7/\" DRAWING TITLE FLOOR PLAN- 1st FLOOR 2 3 5 6 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 Description Main Door Masonry Opening Bedroom Door Room Door Acoustic Door Service room Door Utility Door Toilet Door Toilet Door Gym door Pooja door Grill Gate Sliding Door Sliding Window Sliding Window Sliding Window Casement Window Sliding Window Sliding Window Top Hang & Fixed Window Sliding Window Casement Window Sliding Window Sliding Window Sliding Window Casement Window Casement Window Fixed Window Ventilator Ventilator OPI DI GG SD WI W7 WIO WII KWI KW2 SWI VI Height BOTTOM Lintel No.s 4 4 1 1\" Drop LOBBY 16-2\" x 101-9\" Refer handrail detail ARCHITECTS THIS DRAWING IS A COPYRIGHT. IT IS NOT TO BE REPRODUCED,COPIED HANDED OVER TO A THIRD PARTY OR USED FOR ANY OTHER PURPOSE OTHER THAN FOR THE PROJECT INVOLVED. *ALL DRAWINGS AND DIMENSIONS ARE IN FT 10 11 12 13 M. BEDR OM 161-0\" x 16 1.5\" ward10be 4'0'1 40\" 12'9\" , BEAM 06 BOTTOM 7'0'1 Staircase detail Beam bottorn 31'-6\" STUDIO 7 ARCHITECTS / MMM/ 19 18 17 1 15 4+11 Refer MS Fins detail CLIENTS 2 65 TOTAL REVISION Plot No. PP Ill, Janani's Shri Nilayam Semmencherry, Chennai - 600 119. Mr. and Mrs. Adithya PROJECT Mr.Adithya residence SCALE DATE 1:100 21-08-2024 DRAWING CODE DRAWN CHECKED",
      "C 1 1'-6\" 2'-6 6- 14'6\" BEAM 06 BEAM Area Statement: Site Area: 4310.13 Sq.ft Stilt Floor area: 2645.54 sq.ft 1st Floor area: 2674.24 sq.ft 2nd Floor area: 2652.86 sq.ft Terrace Floor area: 846.56 sq.ft Total Buildup Area: 8819.22 sq.ft Refer MS Fins d tail KIDS BEDRO Refer Sun shade detail TOILET +22'4\"lvl 1 \" Drop +22'5\"lvl 1\" Drop GUES BEDROOM 123 5\" x 14'-3\" DI DI read:l '0\" iser:5.75\" + 2'6\"lvi Refer ha Refer MS Fins d tail Refer Duct detail THIS DRAWING IS A COPYRIGHT. IT IS NOT TO BE REPRODUCED,COPIED HANDED OVER TO A THIRD PARTY OR USED FOR ANY OTHER PURPOSE OTHER THAN FOR THE PROJECT INVOLVED. *ALL DRAWINGS AND DIMENSIONS ARE IN FT +22'5 1\" Drop vl 6 HOME THEATRE 20'-9\" x 14'-3\" 03 1 Drop W RDROBE \"\u0007iuiiin 24 25 drail detail 27 28 29 30 31 32 Lift ope Ing as per v ndor SWI I 13 14 15 16 Refer Sun shade detail 1 Drop Refer Duct detail lifi Dbwn ' \" iX5'-0\" TOILET +22'4\"lvi 1 \" Drop TOILET x 11'-10.5 +22'5\"lvl Schedule of Joinery Tag Width OM '-7.51' 2 3 5 6 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 Description Main Door Masonry Opening Bedroom Door Room Door Acoustic Door Service room Door Utility Door Toilet Door Toilet Door Gym door Pooja door Grill Gate Sliding Door Sliding Window Sliding Window Sliding Window Casement Window Sliding Window Sliding Window Top Hang & Fixed Window Sliding Window Casement Window Sliding Window Sliding Window Sliding Window Casement Window Casement Window Fixed Window Ventilator Ventilator OPI DI GG SD WI W7 WIO WII KWI KW2 SWI VI Height BOTTOM 6'6\" Sill DRESSING REA 61-13\" x 61-9\" WARDROBE 02 SH 40 4+22'5\"lvl OBE RESSING REA 1 Drop OPI M. BED 161-0\" x 1 -1. 5\" Lintel No.s BOTTOM 7'0'i SIT OUT 1 T-6\" x 14-6\" Refer handrail detail ARCHITECTS / WWW' / /MM/M,I oooooooooooo Refer MS Fins detpil CLIENTS WARDROBE DRAWING TITLE FLOOR PLAN- 2nd FLOOR 40\" 3'6'1 12'9\" Sta ircase detail Beam 2 65 TOTAL REVISION STUDIO 7 ARCHITECTS Plot No. PP Ill, Janani's Shri Nilayam Semmencherry, Chennai - 600 119. Mr. and Mrs. Adithya PROJECT Mr.Adithya residence SCALE DATE 1:100 21-08-2024 DRAWING CODE DRAWN CHECKED",
      "C D E 45-9\" 17'-6 2'-6\" 14'6\" BEAM 06 BEAM Area Statement: Site Area: 4310.13 Sq.ft Stilt Floor area: 2645.54 sq.ft 1st Floor area: 2674.24 sq.ft 2nd Floor area: 2652.86 sq.ft Terrace Floor area: 846.56 sq.ft Total Buildup Area: 8819.22 sq.ft D2 24 Tread: 1 '0\" Ris r:5.75\" 9-+ 36\"lvl 46 Down 25 45 27 43 28 42 29 41 30 40 31 39 32 38 33 37 34 36 ++34'O\"lvl Refer Duct detail Room 6'3\" x 5'10.75\" Schedule of Joinery Sill 0 6'- \" x 510' Lift o ening r vendor as p GYM 6'-0\" x 21'-0\" Refer Duct detail THIS DRAWING IS A COPYRIGHT. IT IS NOT TO BE REPRODUCED,COPIED HANDED OVER TO A THIRD PARTY OR USED FOR ANY OTHER PURPOSE OTHER THAN FOR THE PROJECT INVOLVED. *ALL DRAWINGS AND DIMENSIONS ARE IN FT 2 3 5 6 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 Description Main Door Masonry Opening Bedroom Door Room Door Acoustic Door Service room Door Utility Door Toilet Door Toilet Door Gym door Pooja door Grill Gate Sliding Door Sliding Window Sliding Window Sliding Window Casement Window Sliding Window Sliding Window Top Hang & Fixed Window Sliding Window Casement Window Sliding Window Sliding Window Sliding Window Casement Window Casement Window Fixed Window Ventilator Ventilator Tag Width OPI DI GG SD WI W7 WIO WII KWI KW2 SWI VI Height BOTTOM 6'6\" Lintel No.s BOTTOM 7'0'i SD CLIENTS Mr. and Mrs. Adithya PROJECT Mr.Adithya residence 40\" 3'6'1 12'9\" Sta ircase detail Beam 2 65 ARCHITECTS TOTAL REVISION DRAWING TITLE FLOOR PLAN- TERRACE FLOOR STUDIO 7 ARCHITECTS Plot No. PP Ill, Janani's Shri Nilayam Semmencherry, Chennai - 600 119. SCALE DATE 1:100 21-08-2024 DRAWING CODE DRAWN CHECKED"
    ],
    "description": "06 WORK - Studio 7 Architects During my time at Studio 7 Architects, I worked as a project architect, taking the lead role in design and overseeing site work. I was responsible for managing site activities, resolving on-site issues, and coordinating the on-site team to ensure smooth project execution. I handled detailed working drawings, documentation, and collaborated with structural consultants, contractors, and vendors. Client handling, material procurement, and conducting on-site inspections were also part of my role."
  },
  {
    "id": "internship_work",
    "index": "07",
    "title": "Internship Work - Betweenlines",
    "category": "Professional Experience",
    "location": "Bangalore & Chennai, India",
    "role": "Trainee Architect (2022)",
    "software": "AutoCAD, SketchUp, V-Ray, Photoshop",
    "start_page": 53,
    "end_page": 65,
    "pages": [
      "53.jpg",
      "54.jpg",
      "55.jpg",
      "56.jpg",
      "57.jpg",
      "58.jpg",
      "59.jpg",
      "60.jpg",
      "61.jpg",
      "62.jpg",
      "63.jpg",
      "64.jpg",
      "65.jpg"
    ],
    "texts": [
      "07 INTERNSHIP - BETWEENLINES 5 month internship work during my 4th academic year in a well established firm in bangalore,lndia. only selected projects",
      "Handloom & Handicraft Museum 1- Program level -To showcase the rich tradition, skill, and variety of Handloom and Handicraft produced in the state of TamilNadu -To design a facility, that will encourage learning, research, novel thinking and collaboration in the field of Handloom and Handicrafts -To be a State cultural icon and a tourist place for both the instate, out state and expats visiting the state -To organise the program through commercial and cultural symbiosis, by blurring the boundary between a gallery and a store 2- Site level 3- Built level 4- Exhibit level ENTIRE WEAVING PROCESS Individual fibres come together to become beautiful fabrics. fez J VisibiliY Commerc4 Com 8tt Source - https://contextbd.com/integrated-handloom-cluster-for-weavers-collectivisation/",
      "2- Site level -To understand and appreciate the existing facility at site and integrate it as part of the proposed development, without disrupting its current operation and position -To understand the location, and topographical features of the site and propose a site plan to benefit the program and the program to benefit the site -To plan for active mobility and pedestrianisation -To plan for public spaces, where subjects of all age, gender and faith feel welcome to enjoy the space. -To integrate landscape as a living, thriving layer around the building, and not restrict it to decorative element Q I.JYban& \u0007t 111' LEGENDS Lobby Area - Main Galleries - Rental Spaces - Amenities - Services - Phase 2 (Non essentials / Desired) - Total - Rental spaces Tools/ History/ Demo centre Gallery Lobby Amenities Services 1,524.53 SFT 14,967.98 SFT 6,814.68 SFT 3,699.79 SFT 2,017.92 SFT 7,391.74 SFT 32,716.85 SFT Phase 2 (Non-essential/Desired) Walkway Circulation Road Vegetation",
      "3.BuiIt level -To keep it universally friendly -To keep it compliant to all statutory laws and guidelines -To keep it local economy, labour, and material friendly -To Keep it representative and communicative of its program, purpose and context to the masses -To work as a billboard for the Program and associated department of Handloom and Handicrafts -To remain responsible in its energy consumption and be a model of sustainable development -To remain taut in the integration of various services and complete the functioning of the building Building edge as gallery nwnnq Billboard for Handloom and Handicraft",
      "MEZZANINE FLOOR PLAN GROUND FLOOR PLAN FIRST FLOOR PLAN 1 - Handloom shops 2 - Handicraft shops 3 - Tools/ History/ Demo centre 4 - Entrance lobby 5 - Gallery 6 - Washrooms 7 - 7D Theatre 8 - History/ Children's area 9 - Cafeteria 10 - Central transition space 11 - Parking lot 12 - Bus parking 1 - Handloom gallery 2 - Handicraft gallery 3 - AV room - Khadi gallery 5 - Resource library (jimiiiu 6 - Store 7 - Washrooms 8 - Collaborative workshops/ Temporary exhibition space 9 - Conference facility 10 - Cafeteria GROUND FLOOR ZONING Rental spaces Tools/ centre Arrentes Serv,ces Phase 2 (tm\u0007essent'J/tksited) Vegetaton Walkwav FIRST FLOOR ZONING l- office space MEZZANINE FLOOR ZONING Office Space Services Phase 2 (Non-essentiaVDesired) Rental spaces Gallery Amenities",
      "NALLI - ANNA NAGAR ( Fluted glass - OPTION ) Nalli is a famous textile brand in India. The focus of the design was to create an design which is unique, contemporary and should have an good value in terms of aesthetics. This option was selected by the clients between the given 2 options. Glass type Fluted glass area Plain glass area Area 2045 S.ft 1345 S.ft 11'1\" 10'9\" Rate /sft Rs 1885 approx. Rs approx. Proposed Projection (5 ft) Plain glass Fluted glass Layers of metal mesh curtains 19'9\" Third floor Plan",
      "NALLI - ANNA NAGAR ( Fluted glass - OPTION 2 ) Nalli is a famous textile brand in India. The focus of the design was to create an design which is unique, contemporary and should have an good value in terms of aesthetics. This option was selected by the clients between the given 2 options. GLASS FIBRE REINFORCED CONCRETE PANELS WITH INLAY BACKLIT TRANSLUCENT CORIAN PANELS 10'9\" 19'9 Second floor Plan 11'1\" Proposed Projections (max.5ft) Plain glass Proposed projections Panel in daylight condition Facade Panel total area Panel in night condition (Lit by external lighting) - 2065 S.ft - Rs:500 - Rs: 1500 /S.ft Panel in daylight condition (backlit) Panel in night condition (backlit) Facade Panel total area - 4000 s.ft - Rs:1500 - Rs:3500 /S.ft",
      "Nalli Fashions Conceptual View ( Chennai ) This project was built accorind to the proposed design and later on additional inputs were needed from the clients side, and I was alloted to design the reqirments which is needed for the design and mural patterns were inspired from famous saree designs and was incorpreated as motif in the elevation of the building. Mural art at Elevation",
      "Maharishi Vedic Health PVT.LTD Maharishi Ayur Veda also holds that perfect health is a state present within every person, that can be chosen by the individual, and that the physical body is a portal to a \"quantum mechanical body\" that exists at the subatomic level where matter and energy are one, and that every organ and process in the body has a quantum equivalent. Tony Nader, called Maharajadhiraj Raja Ram, who is the Sovereign Ruler of the Global Country of World Peace, identifies this concept of \"quantum healing\" with the Maharishi's theories of Vedic Science.l got a chance to design the Maharashi Vedic Health PVT.LTD Punce Zone - C, The design is more focused on blending the building to its surroundings OPTION I MASSING OBTAINED VERTICALLY s.rx4.t\u0007 SHOWER BEO Conceptual plan for Zone - C SITE PLAN S.\u0007X",
      "OPTION 2 The plan is slightly moved compared to the optionl to try giving different foot print as per clients requests. As option 1 had achieved an vertical height so this option was designed with an horizontal spread in the site. so\u0007.4t\u0007 OUT Conceptual plan for Zone - Shoat-R c",
      "BENGALURU NORTH UNIVERSITY KOLAR Bengalur North University Kolar is a famous university located at Kolar, The requirments was to create a design which is rustic and robust design unl liillii! ace."
    ],
    "description": "07 INTERNSHIP - BETWEENLINES 5 month internship work during my 4th academic year in a well established firm in bangalore,lndia. only selected projects"
  },
  {
    "id": "miscellaneous",
    "index": "08",
    "title": "Photography & Art",
    "category": "Miscellaneous",
    "location": "Global",
    "role": "Wildlife Photographer",
    "software": "Lightroom, DSLR Photography",
    "start_page": 66,
    "end_page": 67,
    "pages": [
      "66.jpg",
      "67.jpg"
    ],
    "texts": [
      "08 MISCELLANEOUS WO R KS Raamprakash 14 June 2020 Wildlife photography Follow v 25 Her heart may be pure and good but she should kill to SURVIVE #waterscape #street #anlmal #wlldllfephotography #blrdwatchlng #4hours #patlents Contest awards Animals #402 cgowo 100 Photos I June 2020 '025% Crowd 19th Place Tirupati Chittoor Vellore Kanchipuram nai ntn"
    ],
    "description": "08 MISCELLANEOUS WO R KS Raamprakash 14 June 2020 Wildlife photography Follow v 25 Her heart may be pure and good but she should kill to SURVIVE #waterscape #street #anlmal #wlldllfephotography #blrdwatchlng #4hours #patlents Contest awards Animals #402 cgowo 100 Photos I June 2020 '025% Crowd 19th Place Tirupati Chittoor Vellore Kanchipuram nai ntn"
  }
];
